### ISSUE TITLE
Problem with policies when you decide to pass parameters to methods (allows, denies, ...)

### ISSUE THREAD

**Issue by NathaelB** [adonisjs/bouncer#16] opened 2024-08-02 12:50 UTC
### Package version

3.1.3

### Describe the bug

I'm having a problem when I try to use my policy in my controller.
I've created a `CompanyPolicy` policy with a `view` method.

```ts
async view(payload: JWTPayload, companyId: string) {
  // ...
}
```

Use in the controller

```ts
async show({ params, bouncer }: HttpContext) {
  await bouncer.with(CompanyPolicy).authorize('view', params.id)
}
```

So I get a `TS2554: Expected 1 arguments, but got 2` error.
Looking at the signature of the `authorize` function I have:
```ts
function PolicyAuthorizer<never, typeof CompanyPolicy>.authorize<"store">(     action: "store"): Promise<void>
```

But if I do:
```ts
await bouncer.with(CompanyPolicy).authorize('view' as never, params.id)
```

Now I don't have a problem.

### Reproduction repo

https://github.com/libreconnect/backend

**Comment by patrickphat** [comment] 2024-09-08 07:31
I found that only non async policies got the type safety. If you use async function (like you need to query something inside the policies), there would be type errors.

**Comment by thetutlage** [comment] 2024-09-09 04:54
@patrickphat That issue was fixed a long time back here in this release. https://github.com/adonisjs/bouncer/releases/tag/v3.1.3

Regarding the issue @patrickphat is facing seems like a case of misconfiguration. He is used the `ctx.bouncer` instance, which is configured to pull the user from the `ctx.auth`. Whereas, the policy first argument accepts `JwtPayload`. In that case, the error raised by TypeScript is valid. Because `ctx.bouncer` behind the scenes will pass the `ctx.auth.user` to the `CompanyPolicy.view` method, whereas it accepts `JwtPayload`.

**Comment by benjibenoit** [comment] 2024-09-24 13:50
> Looking at the signature of the `authorize` function I have:
> 
> ```ts
> function PolicyAuthorizer<never, typeof CompanyPolicy>.authorize<"store">(     action: "store"): Promise<void>
> ```
> 
> But if I do:
> 
> ```ts
> await bouncer.with(CompanyPolicy).authorize('view' as never, params.id)
> ```
> 
> Now I don't have a problem.

I have the same problem has described here. My policy is defined as :
![image](https://github.com/user-attachments/assets/e28ba8ae-7653-4623-82a9-4507c878df58)

And in my controller I have :
![image](https://github.com/user-attachments/assets/6b5d4ef2-4c36-439c-8d16-97970271ac1f)

But in the controller, for the denies() I have an error saying "create" should be "never":
![image](https://github.com/user-attachments/assets/2033750e-85af-4d14-b58c-6b1d20b7de28)

**Comment by thetutlage** [comment] 2024-09-25 01:57
@shankiflang What does your `config/auth` file looks like?

**Comment by benjibenoit** [comment] 2024-09-25 09:08
> @shankiflang What does your `config/auth` file looks like?

Here's my current `config/auth`. I haven't updated it since it was generated (I only updated the import):
![image](https://github.com/user-attachments/assets/339c7a8a-55c6-40d2-8932-4d5a7566354f)

And I've noticed that since the beginning I've had this error:
![image](https://github.com/user-attachments/assets/eeace354-6574-4e3a-b728-51b1bf685835)

**Comment by ThisIsMissEm** [comment] 2024-10-03 16:08
What's your `InitializeBouncerMiddleware` look like? Because iirc, it should have this at the end:

```typescript
declare module '@adonisjs/core/http' {
  export interface HttpContext {
    bouncer: Bouncer<
      Exclude<HttpContext['auth']['user'], undefined>,
      typeof abilities,
      typeof policies
    >
  }
}
```

**Comment by benjibenoit** [comment] 2024-10-04 09:30
> And I've noticed that since the beginning I've had this error: ![image](https://private-user-images.githubusercontent.com/32774804/370642828-eeace354-6574-4e3a-b728-51b1bf685835.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgwMzA3MjcsIm5iZiI6MTcyODAzMDQyNywicGF0aCI6Ii8zMjc3NDgwNC8zNzA2NDI4MjgtZWVhY2UzNTQtNjU3NC00ZTNhLWI3MjgtNTFiMWJmNjg1ODM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA0VDA4MjcwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFkZThiYjY2YTczZmZkYmRmMWZmMjlkNWRkMjQ4ODVhNzg5NTkwMjQ3OGE1NDc3Nzc1ZjBkZDVmNTAyNjNkYjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.oz6LUL1X8UaP-a9G6d0iCmdOgkehE1yuPmUMUCOG-GA)

I saw that @RomainLanz had added an export to his repo to remove this error, so I did the same. Like that : 
```ts
declare module '@adonisjs/auth/types' {
  export interface Authenticators extends InferAuthenticators<typeof authConfig> {}
}
```

> What's your `InitializeBouncerMiddleware` look like? Because iirc, it should have this at the end:
> 
> ```ts
> declare module '@adonisjs/core/http' {
>   export interface HttpContext {
>     bouncer: Bouncer<
>       Exclude<HttpContext['auth']['user'], undefined>,
>       typeof abilities,
>       typeof policies
>     >
>   }
> }
> ```
Yep that's what I have.

**Comment by ahmerds** [comment] 2024-10-18 17:40
Hey guys, I have the same problem @shankiflang has described above. For my case it works for some policies and doesn’t work for others, also doesn’t seem to work for async policies (I am using v3.1.3)

**UPDATE for anyone reading this thread:** After a bit of digging, I found the cause of the problem.
If you have multiple authenticators using different models, such as `User` and `Staff` models in your auth config, you need to pass them as types in your policy. Otherwise, the `GetPolicyMethods` function in the Bouncer package will return never.

For example, in your auth config, if you have something like this:
```typescript
const authConfig = defineConfig({
  default: 'api',
  guards: {
    api: tokensGuard({
      provider: tokensUserProvider({
        tokens: 'accessTokens',
        model: () => import('#models/user'),
      }),
    }),
    staff: tokensGuard({
      provider: tokensUserProvider({
        tokens: 'accessTokens',
        model: () => import('#models/staff'),
      }),
    }),
  },
})
``` 
When defining your policies, you need to pass both models as the first argument, like this:
```typescript
// Notice the User | Staff
edit(user: User | Staff, post: Post): AuthorizerResponse {
  return user.id === post.user.id
}
```
If you only use `user: User` or `staff: Staff` the method will not be inferred correctly. Note that you should also check that `user instanceof User` or `staff instanceof Staff` before defining the policy logic

**Comment by benjibenoit** [comment] 2024-10-20 21:46
> **UPDATE for anyone reading this thread:** After a bit of digging, I found the cause of the problem. If you have multiple authenticators using different models, such as `User` and `Staff` models in your auth config, you need to pass them as types in your policy. Otherwise, the `GetPolicyMethods` function in the Bouncer package will return never.


Thanks for the research, but I'm only using one authenticator :
```ts
const authConfig = defineConfig({
  default: 'web',
  guards: {
    web: sessionGuard({
      useRememberMeTokens: false,
      provider: sessionUserProvider({
        model: () => import('#users/models/user'),
      }),
    }),
  },
})
```

But I still have the issue

**Comment by benjibenoit** [comment] 2024-10-22 13:28
Ok, After a bit of digging, I found something. When I put my policies as "async" it doesn't work:
```ts
async update(user: User, postId: UUID): Promise<AuthorizerResponse> {
    return await this.is(user, postId)
}
```
will not work. But this works:
```ts
update(user: User, postId: UUID): AuthorizerResponse {
    return this.is(user, postId)
}
```

**Comment by ahmerds** [comment] 2024-10-22 15:09
> Ok, After a bit of digging, I found something. When I put my policies as "async" it doesn't work:
> 
> ```ts
> async update(user: User, postId: UUID): Promise<AuthorizerResponse> {
>     return await this.is(user, postId)
> }
> ```
> 
> will not work. But this works:
> 
> ```ts
> update(user: User, postId: UUID): AuthorizerResponse {
>     return this.is(user, postId)
> }
> ```

What version of bouncer do you have in your package.json?

**Comment by benjibenoit** [comment] 2024-10-22 15:19
> > Ok, After a bit of digging, I found something. When I put my policies as "async" it doesn't work:
> > ```ts
> > async update(user: User, postId: UUID): Promise<AuthorizerResponse> {
> >     return await this.is(user, postId)
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > will not work. But this works:
> > ```ts
> > update(user: User, postId: UUID): AuthorizerResponse {
> >     return this.is(user, postId)
> > }
> > ```
> 
> What version of bouncer do you have in your package.json?

"@adonisjs/bouncer": "^3.1.3",

**Comment by RomainLanz** [comment] 2024-10-23 06:58
This issue should have been fixed already. Could you share a repository with the minimum amount of code to reproduce the issue?

**Comment by benjibenoit** [comment] 2024-10-23 08:30
> This issue should have been fixed already. Could you share a repository with the minimum amount of code to reproduce the issue?

Yeah : https://github.com/shankiflang/repo-repro-bouncer This repo doesn't work as I haven't setup auth, but you can see the `never` error. In the PostsController, I have on `view`:
```
TS2345: Argument of type string is not assignable to parameter of type never
```

If you remove the async of `view` policy, the error disappears.

**Comment by thetutlage** [comment] 2024-11-05 12:53
@shankiflang 

Turns out the issue is with the return type of the `PostPolicy` you shared. If I remove the return type or update it to `async view(user: User): Promise<boolean | AuthorizationResponse> {`, everything seems to be work fine.

**Comment by thetutlage** [comment] 2024-11-05 12:55
This issue has become crowded with multiple use-cases. I will close it. Please create separate issues for your use-cases.

**Closed as completed by thetutlage** 2024-11-05 12:55 UTC
